concilia_BR381/urls.py
#coding=utf-8
"""concilia_BR381 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from core import views
from content import views as conteudos_views
from django.conf.urls.static import static
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

admin.site.site_title = "Concilia BR-381 e Anel"
admin.site.site_header = "Concilia BR-381 e Anel"
admin.site.index_title = 'Painel administrativo do site'

handler404 = views.page_not_found
handler500 = 'core.views.server_error'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^acervo/$', views.acervo, name='acervo'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobre/$', views.about, name='about'),
    url(r'^imoveis/$', views.imoveis, name='imoveis'),
    url(r'^parceiros/$', views.partners, name='partners'),
    url(r'^cmar/$', views.cmar, name='cmar'),
    url(r'^conselho-executivo/$', conteudos_views.conselho_executivo, name='conselho_executivo'),
    url(r'^plano-de-providencias/$', views.plano_providencias, name='plano_providencias'),
    url(r'^criterios-e-regras/$', views.criterios_regras, name='criterios_regras'),
    url(r'^manual-marca/$', views.manual_marca, name='manual_marca'),
    url(r'^conteudos/', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),
    # Plugins URLs
    # url(r'^tinymce/', include('tinymce.urls')),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^redactor/', include('redactor.urls')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

content/urls.py
#coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^noticias/$', views.news, name='noticias'),
    url(r'^perguntas-frequentes/$', views.perguntas_frequentes, name='perguntas-frequentes'),
    url(r'^acervo/videos/$', views.videos, name='videos'),
    url(r'^acervo/videos/(?P<slug>[\w_-]+)/$', views.youtube_playlist_view, name='youtube_playlist'),
    url(r'^acervo/galeria/$', views.galeria, name='galeria'),
    url(r'^acervo/galeria/(?P<slug>[\-\d\w]+)/$', views.geleria_detalhe, name='galery-detail'),
    url(r'^noticia/(?P<slug>[\-\d\w]+)/$', views.noticia, name='noticia'),
    url(r'^comunidades/$', views.community, name='comunidades'),
    url(r'^comunidade/(?P<slug>[\-\d\w]+)/$', views.comunidade, name='comunidade'),
]

rondon/urls.py
#coding=utf-8
"""rondon URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from core import views
from django.conf.urls.static import static

admin.site.site_title = "Concilia BR 381"
admin.site.site_header = "Concilia BR 381"
admin.site.index_title = 'Painel administrador do site'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobre/$', views.about, name='about'),
    url(r'^duvidas/$', views.duvida, name='faq'),
    url(r'^parceiros/$', views.partners, name='partners'),
    url(r'^conselho-executivo/$', views.conselho_executivo, name='conselho_executivo'),
    url(r'^manual-marca/$', views.manual_marca, name='manual_marca'),
    url(r'^conteudos/', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
# -*- coding: UTF-8 -*-
import os
import json
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from redactor.fields import RedactorField
from photologue.models import Gallery
from builtins import str
from django.template.defaultfilters import slugify



class Noticia(models.Model):
    ''' Modelo para noticias '''

    title = models.CharField(u'Título', max_length=500)
    sub_title = models.CharField(u'Subtítulo', max_length=500, null=True, blank=True)

    text = RedactorField(
        verbose_name=u'Texto', allow_file_upload=True,
        allow_image_upload=True, null=True, blank=True
    )
    published_at = models.DateTimeField(u'Data de publicação', null=True)
    expired_at = models.DateTimeField(u'Data de expiração da notícia', null=True, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    image = models.ImageField(
        upload_to='noticias/images', verbose_name='Imagem de capa para a Notícia',
        null=True, blank=True
    )
    legend_image = models.CharField('Legenda da Imagem', max_length=200, null=True, blank=True)
    credits_image = models.CharField('Creditos da imagem', max_length=200, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Criado por', editable=False)
    notice_origin = models.CharField(u'Fonte da notícia', max_length=200, null=True, blank=True)
    slug = models.SlugField('Identificador', max_length=500, null=False, blank=False, unique=True,
                            help_text="'slug' é um identificador único que será mostrado na url")
    is_public = models.BooleanField(('É Pública ?'), default=True, blank=True,
                                    help_text=('Somente as notícias marcadas como públicas serão apresentadas no site.'))

    class Meta:
        verbose_name = u'Notícia'
        verbose_name_plural = u'Notícias'
        ordering = ['-published_at', 'legend_image']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.title)
        super(Noticia, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('content:noticia', kwargs={'slug': self.slug})

    def has_image(self):
        try:
            if self.image and self.image.size > 0:
                return True
            else:
                return False
        except Exception as err:
            print(u"Não foi possivel verificar o arquivo: ", err)
            return False

    def has_album(self):
        try:
            if self.album:
                return True
            else:
                return False
        except Exception as err:
            print(u"Não foi possivel verificar o arquivo: ", err)
            return False

    def exists_image_in_path(self):
        if os.path.exists(self.image.path):
            return True
        else:
            return False


class Comunidade(models.Model):

    ''' Modelo para comunidades '''

    title = models.CharField('Nome da Vila ou Comunidade', max_length=500)
    text = RedactorField(
        verbose_name=u'Sobre a comunidade', allow_file_upload=True,
        allow_image_upload=True, null=True, blank=True
    )
    lat = models.CharField('Latitude', max_length=100, blank=True, null=False)
    long = models.CharField('Longitude', max_length=100, blank=True, null=False)
    galery = models.ForeignKey(Gallery, verbose_name='Album de Fotos', related_name='galaria', blank=True, null=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Criado por', editable=False, null=True, blank=True)
    slug = models.SlugField('Identificador', max_length=500, null=False, blank=False, unique=True,
                            help_text="'slug' é um identificador único que será mostrado na url")

    class Meta:
        verbose_name = 'Comunidade/Vila'
        verbose_name_plural = 'Comunidades/Vilas'
        ordering = ['title']

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.title)
        super(Comunidade, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('content:comunidade', kwargs={'slug': self.slug})

    def has_album(self):
        try:
            if self.album:
                return True
            else:
                return False
        except Exception as err:
            print(u"Não foi possivel verificar o arquivo: ", err)
            return False

    def get_lat_long(self):
        if self.lat and self.long:
            return {'lat': self.lat, 'lng': self.long}
        else:
            return False


class YoutubeChannel(models.Model):
    """ Modelo para a página de videos que será integrada com youtube """

    UPLOAD = 'UP'
    PLAYLISTS = 'PL'
    FEATURED = 'FE'

    POPUP = 'PO'
    LINK = 'LK'
    INLINE = 'IN'

    DEFAULT_TAB_CHOICES = (
        (UPLOAD, 'Uploads'),
        (PLAYLISTS, 'Playlists'),
        (FEATURED, 'Featured'),
    )

    VIDEO_DISPLAY_MODE = (
        (POPUP, 'popup'),
        (LINK, 'link'),
        (INLINE, 'inline'),
    )

    title = models.CharField(u'Título', max_length=500,  null=False, blank=False)

    image = models.ImageField(
        upload_to='youtube_channel/images', verbose_name='Imagem de apresentação do canal',
        null=False, blank=False
    )

    slug = models.SlugField('Identificador', max_length=500, null=False, blank=False, unique=True,
                            help_text="'slug' é um identificador único que será mostrado na url")

    channel_link = models.CharField(u'Link do canal', max_length=500,
                                    help_text=u"Link do canal no youtube, exemplo: " \
                                              "https://www.youtube.com/user/crashcourse")

    playlist_link = models.CharField(u'Link da playlist', max_length=500, null=True, blank=True,
                                    help_text=u"Link da playlist no youtube, exemplo: " \
                                              "https://www.youtube.com/playlist?list=PL6_h4dV9kuuIOBDKgxu3q9DpvvJFZ6fB5")

    max_results = models.IntegerField(u'Máximo de resultados por página', default=9, help_text=u"O valor padrão é 9")

    default_tab = models.CharField(
        max_length=2,
        choices=DEFAULT_TAB_CHOICES,
        default=UPLOAD,
    )

    video_display_mode = models.CharField(
        max_length=2,
        choices=VIDEO_DISPLAY_MODE,
        default=POPUP,
    )
    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    class Meta:
        verbose_name = u'Galeria de vídeos do youtube'
        verbose_name_plural = 'Galerias de vídeos do youtube'
        ordering = ['created_at']

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.title)
        super(YoutubeChannel, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def has_image(self):
        try:
            if self.image and self.image.size > 0:
                return True
            else:
                return False
        except Exception as err:
            print(u"Não foi possivel verificar o arquivo: ", err)
            return False

    def get_absolute_url(self):
        return reverse('content:youtube_playlist', kwargs={'slug': self.slug})

    def exists_image_in_path(self):
        if os.path.exists(self.image.path):
            return True
        else:
            return False


class Timeline(models.Model):
    """ Modelo para eventos da linha do tempo - Página index """

    title = models.CharField(u'Título do evento', max_length=500)
    event_date = models.DateField('Data do evento', null=False, blank=True)
    text = models.TextField(verbose_name='Texto')
    image = models.ImageField(
        upload_to='timeline/images', verbose_name='Imagem de apresentação',
        null=True, blank=True
    )
    legend_image = models.CharField('Legenda da imagem', max_length=200, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Criado por', editable=False, null=True,
                               blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    class Meta:
        verbose_name = 'Evento da linha do tempo'
        verbose_name_plural = 'Eventos da linha do tempo'
        ordering = ['event_date']

    def __str__(self):
        return self.title

    def has_image(self):
        try:
            if self.image and self.image.size > 0:
                return True
            else:
                return False
        except Exception as err:
            print(u"Não foi possivel verificar o arquivo: ", err)
            return False

    def exists_image_in_path(self):
        if os.path.exists(self.image.path):
            return True
        else:
            return False


class CategoryFaq(models.Model):

    name = models.CharField('Nome da categoria', max_length=100)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria de perguntas frequentes'
        verbose_name_plural = 'Categorias de perguntas frequentes'
        ordering = ['name']

    def __str__(self):
        return self.name


class Faq(models.Model):

    question = models.CharField('Pergunta', max_length=500, help_text=u"Pergunta que será apresentada no site")
    answer = models.TextField('Resposta', max_length=1000, help_text=u"Resposta para a pergunta que será apresentada no site")

content/templates/content/_comunidade.html
{% extends "base.html" %}

{% block title %}
    {{ comunidade }} | {{ block.super }}
{% endblock  %}

{% block content %}
<style>
     #map {
        height: 500px;
        width: 100%;
       }

 </style>
<section class="section-about">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="header-title">{{ comunidade }}</h1>
        </div>
    </div>
</section>

<section>
    <div class="row">
       {{comunidade.text |safe }}
    </div>
</section>
{% if comunidade.get_lat_long %}
<section >
    <div class="row" id="map">

    </div>
</section>

<script>
     function initMap() {

        var latitude = parseFloat("{{comunidade.lat}}");
        var longitude = parseFloat("{{comunidade.long}}");
        var coords_comunidade = {lat: latitude, lng: longitude};
        var icone = '/static/img/icones/pin.png';
        var comunidade_name = '{{comunidade}}';

        var icon = {
            url: icone,
        };

        map = new google.maps.Map(document.getElementById('map'), {
          center: new google.maps.LatLng(latitude, longitude),
          zoom: 18,
          mapTypeId: 'satellite', // Map types: roadmap, hybrid, terrain, satellite

        });

        var marker = new google.maps.Marker({
          position: coords_comunidade,
          map: map,
          icon: icon,
          //label: comunidade_name,
        });


     };
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAPCEFB2GTWm_rCGIRbFmOy88OGTWuwupk&callback=initMap"
    async defer></script>


{% endif %}
{% endblock  %}

content/templates/content/_noticia.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{ noticia }} | {{ block.super }}
{% endblock  %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/noticias.css' %}" />

<section class="section-about">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{% url 'index' %}">Início</a></li>
          <li><a href="{% url 'content:noticias' %}">Notícias</a></li>
          <li><a href="{% url 'content:noticia' noticia.slug %}">{{ noticia }}</a></li>
        </ol>
    </div>
</section>
<section>
<div class="row content-head">
    <div class="col-sm-12 medium-centered">
        <h1 class="content-head__title">{{ noticia }}</h1>
    </div>
    {% if noticia.sub_title %}
    <div class="col-sm-12 ">
        <h2 class="content-head__subtitle">{{noticia.sub_title}}</h2>
    </div>
    {% endif %}
    <div class="row content-share-bar">
        <div class="col-sm-12 content-share-bar__container">
            <div class="mc-show-later share-bar share-bar-container share-theme-minimal">
              <hr class="header-divider">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <article>
            <div class="mc-column mc-show-later">
                <div class="content-meta-info">
                    <p class="content-meta-info__from">
                        <span>Por {{noticia.author}} </span> <br /> Publicado em {{noticia.published_at|date:"d/m/Y" }}
                    </p>
                </div>
            </div>
            {% if noticia.image %}
                {% if noticia.credits_image %}
                    <span style="font-size: 11px; font-weight: normal;float: right;">{{noticia.credits_image}}</span>
                {% endif %}
                <img src="{{noticia.image.url}}" style="width: 100%;"/>
                {% if noticia.legend_image %}
                <div class="content-media__description-centered ">
                    <p class="content-media__description">
                        <i class="content-media__description__icon theme-color-primary">
                            <!-- Icone foto legenda -->
                            <svg xmlns="http://www.w3.org/2000/svg" width="13.5px" height="11.25px" viewBox="0 0 13 12">
                                <ellipse id="Oval" cx="6.5" cy="6.7826087" rx="2" ry="2.08695652"></ellipse>
                                <path d="M4.625,0.260869565 L3.48125,1.56521739 L1.5,1.56521739 C0.8125,1.56521739 0.25,2.15217391 0.25,2.86956522 L0.25,10.6956522 C0.25,11.4130435 0.8125,12 1.5,12 L11.5,12 C12.1875,12 12.75,11.4130435 12.75,10.6956522 L12.75,2.86956522 C12.75,2.15217391 12.1875,1.56521739 11.5,1.56521739 L9.51875,1.56521739 L8.375,0.260869565 L4.625,0.260869565 L4.625,0.260869565 Z M6.5,10.0434783 C4.775,10.0434783 3.375,8.5826087 3.375,6.7826087 C3.375,4.9826087 4.775,3.52173913 6.5,3.52173913 C8.225,3.52173913 9.625,4.9826087 9.625,6.7826087 C9.625,8.5826087 8.225,10.0434783 6.5,10.0434783 L6.5,10.0434783 Z" id="Shape">
                                </path>
                            </svg>
                        </i>
                        <span class="content-media__description__caption" style="font-size: 12px;">{{noticia.legend_image}} </span> </p>
                </div>
                {% endif %}

            {% endif %}

            {{noticia.text |safe }}
        </article>
        </div>
    </div>
</div>
</section>
{% endblock  %}

content/templates/content/_noticias.html
 {% if noticia %}
<div class="columns small-12 margin-bottom-50">
        <div>
            <h3>
                 <a href="{% url 'content:noticia' noticia.pk %}" style="color: #312d2d;">
                    {{noticia}}
                </a>
            </h3>
            <h6 class="subheader">
                {{noticia.sub_title}}
                <br />
                <small>
                    <i class="fi-clock"></i>
                        Postado em {{noticia.published_at}} por {{noticia.author}}
                </small>
            </h6>
            {% if noticia.has_image %}
               <a href="{% url 'content:noticia' noticia.pk %}">
                   <img src="{{noticia.image.url}}" class="img-responsive img-thumbnail banner-img" alt="{{noticia}}">
               </a>
            {% endif %}
            <section>
                <p>
                    {{noticia.text|truncatechars_html:270|safe }}
                </p>
            </section>
            <section>
                <p class="text-right">
                    <a href="{% url 'content:noticia' noticia.pk %}" class="">Continue lendo →</a>
                </p>
            </section>
        </div>
 </div>
 {% endif %}

content/templates/content/comunidade.html
{% extends "base.html" %}

{% block title %}
    {{ comunidade }} | {{ block.super }}
{% endblock  %}

{% block content %}

<div class="row">
    <div class="column small-12 large-8">
        <article>
            <h1><strong>{{ comunidade }}</strong></h1>
        </article>
    </div>
</div>
<div class="row">
        {{comunidade.about |safe }}
</div>


{% endblock  %}

content/templates/content/gallery.html
{% extends "base.html" %}

{% block title %} Galeria de Fotos | {{ block.super }} {% endblock %}

{% block content %}
<section class="section-about" style="min-height: 600px;">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="title-header-section">Álbuns</h1>
        </div>
    </div>
    <div class="row">
        {% for galeria in galeria_fotos %}
            {% if galeria.photo_count != 0 %}
                <div class="col-sm-6">
                      <a href="{% url 'content:galery-detail' galeria.slug %}">
                          <div class="view photo-list-album-view awake"
                             style="transform: translate(0px, 8px);width: 95%;height: 290px;background-image: url({{galeria.photos.latest.image.url}});">

                              <a class="interaction-view avatar photo-list-album album ginormous" href="{% url 'content:galery-detail' galeria.slug %}" title="{{galeria}}" >
                                  <div class="photo-list-album-interaction dark has-actions">
                                    <a class="overlay" href="{% url 'content:galery-detail' galeria.slug %}">
                                    <div class="interaction-bar">
                                        <div class="metadata">

                                            <h4 class="album-title">{{galeria}}</h4>
                                            {% if galeria.photo_count == 1 %}
                                                <span class="album-photo-count secondary">{{galeria.photo_count}} foto</span>
                                            {% endif %}

                                            {% if galeria.photo_count > 1 %}
                                                <span class="album-photo-count secondary">{{galeria.photo_count}} fotos</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                        </a>
                                </div>
                              </a>

                          </div>
                      </a>
                </div>
            {% endif %}
        {% endfor %}
        {% if galeria_fotos.count == 0 %}
                <div class="center-text col-sm-12">
                    <h1>Nenhum álbum de fotos encontrado :(</h1>
                </div>
        {% endif %}
    </div>
</section>
{% endblock %}

content/templates/content/gallery_detail.html
{% extends "base.html" %}

{% load i18n %}

{% load thumbnail %}

{% load static %}

{% block title %}{{ gallery.title }}{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/smartphoto.min.css' %}" />
<script src="{% static 'js/smartphoto.js' %}"></script>

<!-- BREADCRUMB -->
<section class="section-about" style="margin-bottom: 0px;">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{% url 'index' %}">Início</a></li>
          <li><a href="{% url 'acervo' %}">Acervo</a></li>
		  <li><a href="{% url 'content:galeria' %}">Fotos</a></li>
          <li><a href="{% url 'content:galery-detail' gallery.slug %}">{{ gallery.title }}</a></li>
        </ol>
    </div>
</section>
<!-- END BREADCRUMB -->

<!-- Galery Title -->
<section>
    <div class="row">
        <div class="col-sm-12">
            <h1 class="title-header-section">{{ gallery.title }}</h1>
			<p class="muted"><small>{% trans "Publicado em" %} {{ gallery.date_added }}</small></p>
        </div>
    </div>
</section>
<!-- END GALERY TITLE -->

<!-- Galery Description -->
{% if gallery.description %}
<section>
	<div class="row">
		<div class="col-sm-12" style=" text-align: justify; padding-bottom: 50px;">
			<p>{{ gallery.description|safe }}</p>
		</div>
	</div>
</section>
{% endif %}
<!-- End Galery Description -->
<style>

.module {
    width: 100%;
    height: 200px;
    position: relative;
    overflow: hidden;
    margin: 5px;
}
.module > header {
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  padding: 20px 10px;
}
.module > header > h1 {
	margin: 0px;
    color: white;
    text-shadow: 1px 1px 1px black;
    font-weight: bold;
    font-size: 1em;
}

</style>

<!-- Galery Itens -->
<section>
		<div class="row" style="margin-bottom: 20px;">
		{% for photo in gallery.public %}
			<div class="col-sm-4">
				<a href="{{ photo.image.url}}" class="js-img-viwer" data-caption="{{ photo.title }}" data-id="{{ photo.title }}">
					<div class="module" style="background: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.4)); background-size: cover;">
						<img src="{{photo.image.url}}" style="height: 100%;width: 100%;" alt="{{ photo.title }}" />
					  <header>
						<h1> {{ photo.title }} </h1>
						{% if photo.credits_image %}
							<h1>Foto de {{photo.credits_image}}</h1>
						{% endif %}
					  </header>
					</div>
				</a>
			</div>
			<!--</a>-->
		{% if forloop.counter|divisibleby:3 %}
		</div>
		<div class="row" style="margin-bottom: 20px;">
			{% endif %}
		{% endfor %}
		</div>
</section>
<!-- End Galery Itens -->

<script>
	document.addEventListener('DOMContentLoaded',function(){
		var photo = new smartPhoto(".js-img-viwer");
	});
</script>
{% endblock %}

content/templates/content/video_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %} Vídeo | {{ block.super }} {% endblock %}

{% block content %}



<!-- Import plugin -->
<link href="{% static 'plugins/youmax-classic/css/youmax.min.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'plugins/youmax-classic/js/youmax.min.js' %}"></script>
<!-- end imports -->
<section class="section-about">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{% url 'index' %}">Início</a></li>
          <li><a href="{% url 'acervo' %}">Acervo</a></li>
          <li><a href="{% url 'content:videos' %}">Vídeos</a></li>
          <li class="active">{{playlist}}</li>
        </ol>
    </div>
</section>

<style>
    .youmax{
            background-color: #FFF;
    }

    .yl-header {
                background-color: rgba(101, 93, 93, 0);
    }

    .yl-channel-name {
        font-size: 1.8em;
        color: #444;
    }

    .yl-load-more-button {
        background-color: #fff;
        box-shadow: none;
    }

</style>
<section class="section-about">
    <div class="row">
        <!--Youmax Container-->
            <div class="youmax"></div>
        <!-- ends -->
    </div>
</section>

<!-- Youmax Call -->
    <script>
        $(document).ready(function(){

            $(".youmax").youmax({
                apiKey:"{{YOUTUBE_API_KEY}}",

                channelLink:"{{playlist.channel_link}}",

                {% if playlist.playlist_link %}
                    playlistLink:"{{playlist.playlist_link}}",
                {% endif %}

                defaultTab:"{{playlist.get_default_tab_display}}",         //Uploads|Playlists|Featured
                videoDisplayMode:"{{playlist.get_video_display_mode_display}}",       //popup|link|inline

                maxResults:"{{playlist.max_results}}",
                autoPlay:false,
                displayFirstVideoOnLoad:true,       //for inline video display mode only


                responsiveBreakpoints   :[600,900,2000,2500],

                loadMoreText            :"<i class=\"fa fa-plus\"></i>&nbsp;&nbsp;Mostrar mais vídeos..",
                previousButtonText      :"<i class=\"fa fa-angle-left\"></i>&nbsp;&nbsp;Anterior",
                nextButtonText          :"Próximo&nbsp;&nbsp;<i class=\"fa fa-angle-right\"></i>",
                loadingText             :"Carregando...",
                //allDoneText             :"<i class=\"fa fa-times\"></i>&nbsp;&nbsp;All done..",
                allDoneText             : "",

                hideHeader              :false,
                hideTabs                :true,
                hideLoadingMechanism    :false,


            });
        });
    </script>
<!-- ends -->

{% endblock %}