concilia_BR381/urls.py
#coding=utf-8
"""concilia_BR381 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from core import views
from content import views as conteudos_views
from django.conf.urls.static import static
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

admin.site.site_title = "Concilia BR-381 e Anel"
admin.site.site_header = "Concilia BR-381 e Anel"
admin.site.index_title = 'Painel administrativo do site'

handler404 = views.page_not_found
handler500 = 'core.views.server_error'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^acervo/$', views.acervo, name='acervo'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobre/$', views.about, name='about'),
    url(r'^imoveis/$', views.imoveis, name='imoveis'),
    url(r'^parceiros/$', views.partners, name='partners'),
    url(r'^cmar/$', views.cmar, name='cmar'),
    url(r'^conselho-executivo/$', conteudos_views.conselho_executivo, name='conselho_executivo'),
    url(r'^plano-de-providencias/$', views.plano_providencias, name='plano_providencias'),
    url(r'^criterios-e-regras/$', views.criterios_regras, name='criterios_regras'),
    url(r'^manual-marca/$', views.manual_marca, name='manual_marca'),
    url(r'^conteudos/', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),
    # Plugins URLs
    # url(r'^tinymce/', include('tinymce.urls')),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^redactor/', include('redactor.urls')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

photologue/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from .views import PhotoListView, PhotoDetailView, GalleryListView, \
    GalleryDetailView, PhotoArchiveIndexView, PhotoDateDetailView, PhotoDayArchiveView, \
    PhotoYearArchiveView, PhotoMonthArchiveView, GalleryArchiveIndexView, GalleryYearArchiveView, \
    GalleryDateDetailView, GalleryDayArchiveView, GalleryMonthArchiveView, GalleryDateDetailOldView, \
    GalleryDayArchiveOldView, GalleryMonthArchiveOldView, PhotoDateDetailOldView, \
    PhotoDayArchiveOldView, PhotoMonthArchiveOldView

"""NOTE: the url names are changing. In the long term, I want to remove the 'pl-'
prefix on all urls, and instead rely on an application namespace 'photologue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing 'pl-' prefix for a couple of releases.

"""


urlpatterns = [
    url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
        GalleryDateDetailView.as_view(month_format='%m'),
        name='gallery-detail'),
    url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
        GalleryDayArchiveView.as_view(month_format='%m'),
        name='gallery-archive-day'),
    url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
        GalleryMonthArchiveView.as_view(month_format='%m'),
        name='gallery-archive-month'),
    url(r'^gallery/(?P<year>\d{4})/$',
        GalleryYearArchiveView.as_view(),
        name='pl-gallery-archive-year'),
    url(r'^gallery/$',
        GalleryArchiveIndexView.as_view(),
        name='pl-gallery-archive'),
    url(r'^$',
        RedirectView.as_view(
            url=reverse_lazy('photologue:pl-gallery-archive'), permanent=True),
        name='pl-photologue-root'),

    url(r'^gallery/(?P<slug>[\-\d\w]+)/$',
        GalleryDetailView.as_view(), name='pl-gallery'),

    url(r'^gallerylist/$',
        GalleryListView.as_view(),
        name='gallery-list'),

    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
        PhotoDateDetailView.as_view(month_format='%m'),
        name='photo-detail'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
        PhotoDayArchiveView.as_view(month_format='%m'),
        name='photo-archive-day'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
        PhotoMonthArchiveView.as_view(month_format='%m'),
        name='photo-archive-month'),
    url(r'^photo/(?P<year>\d{4})/$',
        PhotoYearArchiveView.as_view(),
        name='pl-photo-archive-year'),
    url(r'^photo/$',
        PhotoArchiveIndexView.as_view(),
        name='pl-photo-archive'),

    url(r'^photo/(?P<slug>[\-\d\w]+)/$',
        PhotoDetailView.as_view(),
        name='pl-photo'),
    url(r'^photolist/$',
        PhotoListView.as_view(),
        name='photo-list'),

    # Deprecated URLs.
    url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
        GalleryDateDetailOldView.as_view(),
        name='pl-gallery-detail'),
    url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
        GalleryDayArchiveOldView.as_view(),
        name='pl-gallery-archive-day'),
    url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
        GalleryMonthArchiveOldView.as_view(),
        name='pl-gallery-archive-month'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
        PhotoDateDetailOldView.as_view(),
        name='pl-photo-detail'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
        PhotoDayArchiveOldView.as_view(),
        name='pl-photo-archive-day'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
        PhotoMonthArchiveOldView.as_view(),
        name='pl-photo-archive-month')
]

rondon/urls.py
#coding=utf-8
"""rondon URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from core import views
from django.conf.urls.static import static

admin.site.site_title = "Concilia BR 381"
admin.site.site_header = "Concilia BR 381"
admin.site.index_title = 'Painel administrador do site'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobre/$', views.about, name='about'),
    url(r'^duvidas/$', views.duvida, name='faq'),
    url(r'^parceiros/$', views.partners, name='partners'),
    url(r'^conselho-executivo/$', views.conselho_executivo, name='conselho_executivo'),
    url(r'^manual-marca/$', views.manual_marca, name='manual_marca'),
    url(r'^conteudos/', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photologue/views.py
import warnings

from django.views.generic.dates import ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView, \
    YearArchiveView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse

from .models import Photo, Gallery


# Gallery views.

class GalleryListView(ListView):
    queryset = Gallery.objects.on_site().is_public()
    paginate_by = 20


class GalleryDetailView(DetailView):
    queryset = Gallery.objects.on_site().is_public()


class GalleryDateView(object):
    queryset = Gallery.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class GalleryDateDetailView(GalleryDateView, DateDetailView):
    pass


class GalleryArchiveIndexView(GalleryDateView, ArchiveIndexView):
    pass


class GalleryDayArchiveView(GalleryDateView, DayArchiveView):
    pass


class GalleryMonthArchiveView(GalleryDateView, MonthArchiveView):
    pass


class GalleryYearArchiveView(GalleryDateView, YearArchiveView):
    make_object_list = True

# Photo views.


class PhotoListView(ListView):
    queryset = Photo.objects.on_site().is_public()
    paginate_by = 20


class PhotoDetailView(DetailView):
    queryset = Photo.objects.on_site().is_public()


class PhotoDateView(object):
    queryset = Photo.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class PhotoDateDetailView(PhotoDateView, DateDetailView):
    pass


class PhotoArchiveIndexView(PhotoDateView, ArchiveIndexView):
    pass


class PhotoDayArchiveView(PhotoDateView, DayArchiveView):
    pass


class PhotoMonthArchiveView(PhotoDateView, MonthArchiveView):
    pass


class PhotoYearArchiveView(PhotoDateView, YearArchiveView):
    make_object_list = True


# Deprecated views.

class DeprecatedMonthMixin(object):

    """Representation of months in urls has changed from a alpha representation ('jan' for January)
    to a numeric representation ('01' for January).
    Properly deprecate the previous urls."""

    query_string = True

    month_names = {'jan': '01',
                   'feb': '02',
                   'mar': '03',
                   'apr': '04',
                   'may': '05',
                   'jun': '06',
                   'jul': '07',
                   'aug': '08',
                   'sep': '09',
                   'oct': '10',
                   'nov': '11',
                   'dec': '12', }

    def get_redirect_url(self, *args, **kwargs):
        print('a')
        warnings.warn(
            DeprecationWarning('Months are now represented in urls by numbers rather than by '
                               'their first 3 letters. The old style will be removed in Photologue 3.4.'))


class GalleryDateDetailOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-detail', kwargs={'year': kwargs['year'],
                                                            'month': self.month_names[kwargs['month']],
                                                            'day': kwargs['day'],
                                                            'slug': kwargs['slug']})


class GalleryDayArchiveOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-archive-day', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']],
                                                                 'day': kwargs['day']})


class GalleryMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(GalleryMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:gallery-archive-month', kwargs={'year': kwargs['year'],
                                                                   'month': self.month_names[kwargs['month']]})


class PhotoDateDetailOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-detail', kwargs={'year': kwargs['year'],
                                                          'month': self.month_names[kwargs['month']],
                                                          'day': kwargs['day'],
                                                          'slug': kwargs['slug']})


class PhotoDayArchiveOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-archive-day', kwargs={'year': kwargs['year'],
                                                               'month': self.month_names[kwargs['month']],
                                                               'day': kwargs['day']})


class PhotoMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('photologue:photo-archive-month', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']]})

photologue/contrib/old_style_templates/templates/photologue/gallery_archive.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Latest Photo Galleries{% endblock %}

{% block content %}

<h1>Latest Photo Galleries</h1>

{% if latest %}
    {% for gallery in latest %}
    <div class="photo-gallery">
        <h2><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></h2>
        {% for photo in gallery.sample %}
        <div class="gallery-photo">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" class="{% block gallery-photo-class %}{% endblock %}" alt="{{ photo.title }}"/></a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% else %}
    <p>No galleries were found.</p>
{% endif %}

<p><a href="{% url 'photologue:gallery-list' %}">View all galleries.</a></p>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/gallery_archive_day.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Galleries for {{ day|date }}{% endblock %}

{% block content %}

<h1>Galleries for {{ day|date }}</h1>

{% if object_list %}
    {% for gallery in object_list %}
    <div class="photo-gallery">
        <h2>{{ gallery.title }}</h2>
        {% for photo in gallery.sample %}
        <div class="gallery-photo">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% else %}
    <p>No galleries were found.</p>
{% endif %}

<p><a href="{% url 'photologue:gallery-list' %}">View all galleries.</a></p>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/gallery_archive_month.html
w{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Galleries for {{ month|date:"F Y" }}{% endblock %}

{% block content %}

<h1>Galleries for {{ month|date:"F Y" }}</h1>

{% if object_list %}
    {% for gallery in object_list %}
    <div class="photo-gallery">
        <h2>{{ gallery.title }}</h2>
        {% for photo in gallery.sample %}
        <div class="gallery-photo">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
{% else %}
    <p>No galleries were found.</p>
{% endif %}

<p><a href="{% url 'photologue:gallery-list' 1 %}">View all galleries.</a></p>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/gallery_archive_year.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Galleries for {{ year }}{% endblock %}

{% block content %}

<h1>Galleries for {{ year }}</h1>
<ul>
{% for date in date_list %}
<li><a href="{{ date|date:"M"|lower }}/">{{ date|date:"F" }}</a></li>
{% endfor %}
</ul>

<p><a href="{% url 'photologue:gallery-list' %}">View all galleries.</a></p>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/gallery_detail.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}

<h1>{{ object.title }}</h1>
<h2>Originally published {{ object.date_added|date:"l, F jS, Y" }}</h2>
{% if object.description %}<p>{{ object.description }}</p>{% endif %}
<div class="photo-gallery">
    {% for photo in object.public %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" class="{% block gallery-photo-class %}{% endblock %}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
</div>
<p><a href="{% url 'photologue:gallery-list' %}">View all galleries</a></p>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/gallery_list.html
{% extends "photologue/root.html" %}

{% load url from future %}

{% block title %}All Galleries{% endblock %}

{% block content %}

<h1>All galleries</h1>

{% if object_list %}

    {% for gallery in object_list %}
    <div class="photo-gallery">
        <h2><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></h2>
        {% for photo in gallery.sample %}
        <div class="gallery-photo">
            <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" class="{% block gallery-photo-class %}{% endblock %}" alt="{{ photo.title }}"/></a>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

{% else %}
    <p>No galleries were found.</p>
{% endif %}

{% if is_paginated %}
<p>{{ page_obj.paginator.count }} galleries total.</p>
<div id="page_controls">
    <p>{% if page_obj.has_previous %}
    	<a href="{% url 'photologue:gallery-list' %}?page={{ page_obj.previous_page_number }}">Previous</a> | {% endif %} page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} {% if page_obj.has_next %}| <a href="{% url 'photologue:gallery-list' %}?page={{ page_obj.next_page_number }}">Next</a>{% endif %}
    </p>
</div>
{% endif %}

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/photo_archive.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Latest Photos{% endblock %}

{% block content %}

<h1>Latest Photos</h1>

{% if latest %}
    {% for photo in latest %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
{% else %}
<p>No photos were found.</p>
{% endif %}
<p><a href="{% url 'photologue:photo-list' %}">View all photographs</a></p>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/photo_archive_day.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Photos for {{ day|date }}{% endblock %}

{% block content %}

<h1>Photos for {{ day|date }}</h1>

{% if object_list %}
    {% for photo in object_list %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
{% else %}
<p>No photos were found.</p>
{% endif %}
<p><a href="{% url 'photologue:photo-list' %}">View all photographs</a></p>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/photo_archive_month.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}Photos for {{ month|date:"F Y" }}{% endblock %}

{% block content %}

<h1>Photos for {{ month|date:"F Y" }}</h1>

{% if object_list %}
    {% for photo in object_list %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
{% else %}
<p>No photos were found.</p>
{% endif %}
<p><a href="{% url 'photologue:photo-list' %}">View all photographs</a></p>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/photo_archive_year.html
{% extends "photologue/root.html" %}

{% block title %}Galleries for {{ year }}{% endblock %}

{% block content %}

<h1>Photos for {{ year }}</h1>
<ul>
{% for date in date_list %}
<li><a href="{{ date|date:"M"|lower }}/">{{ date|date:"F" }}</a></li>
{% endfor %}
</ul>

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/photo_detail.html
{% extends "photologue/root.html" %}

{% load photologue_tags %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}

<h1>{{ object.title }}</h1>
<div class="gallery-photo">
    <a href="{{ object.image.url }}"><img src="{{ object.get_display_url }}" class="{% block gallery-photo-class %}{% endblock %}" alt="{{ object.title }}"/></a>
    {% if object.caption %}<p>{{ object.caption }}</p>{% endif %}
</div>
{% if object.public_galleries %}
<h2>This photo is found in the following galleries:</h2>
<ol>
{% for gallery in object.public_galleries %}
    <li>{%previous_in_gallery object gallery%} <a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a> {%next_in_gallery object gallery%}</li>
{% endfor %}
</ol>
{% endif %}

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/photo_list.html
{% extends "photologue/root.html" %}
{% load url from future %}

{% block title %}All Photos{% endblock %}

{% block content %}

<h1>All Photos</h1>

{% if object_list %}
    {% for photo in object_list %}
    <div class="gallery-photo">
        <a href="{{ photo.get_absolute_url }}"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
    </div>
    {% endfor %}
{% else %}
<p>No photos were found.</p>
{% endif %}

{% if is_paginated %}
<p>{{ paginator.count }} photos total.</p>
<div id="page_controls">
    <p>{% if page_obj.has_previous %}<a href="{% url 'photologue:photo-list' %}?page={{ page_obj.previous_page_number }}">Previous</a> | {% endif %} page {{ page_obj.number }} of {{ paginator.num_pages }} {% if page_obj.has_next %}| <a href="{% url 'photologue:photo-list' %}?page={{ page_obj.next_page_number }}">Next</a>{% endif %}</p>
</div>
{% endif %}

{% endblock %}

photologue/contrib/old_style_templates/templates/photologue/root.html
{% extends "base.html" %}