concilia_BR381/urls.py
#coding=utf-8
"""concilia_BR381 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from core import views
from content import views as conteudos_views
from django.conf.urls.static import static
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

admin.site.site_title = "Concilia BR-381 e Anel"
admin.site.site_header = "Concilia BR-381 e Anel"
admin.site.index_title = 'Painel administrativo do site'

handler404 = views.page_not_found
handler500 = 'core.views.server_error'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^acervo/$', views.acervo, name='acervo'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobre/$', views.about, name='about'),
    url(r'^imoveis/$', views.imoveis, name='imoveis'),
    url(r'^parceiros/$', views.partners, name='partners'),
    url(r'^cmar/$', views.cmar, name='cmar'),
    url(r'^conselho-executivo/$', conteudos_views.conselho_executivo, name='conselho_executivo'),
    url(r'^plano-de-providencias/$', views.plano_providencias, name='plano_providencias'),
    url(r'^criterios-e-regras/$', views.criterios_regras, name='criterios_regras'),
    url(r'^manual-marca/$', views.manual_marca, name='manual_marca'),
    url(r'^conteudos/', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),
    # Plugins URLs
    # url(r'^tinymce/', include('tinymce.urls')),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^redactor/', include('redactor.urls')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

content/urls.py
#coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^noticias/$', views.news, name='noticias'),
    url(r'^perguntas-frequentes/$', views.perguntas_frequentes, name='perguntas-frequentes'),
    url(r'^acervo/videos/$', views.videos, name='videos'),
    url(r'^acervo/videos/(?P<slug>[\w_-]+)/$', views.youtube_playlist_view, name='youtube_playlist'),
    url(r'^acervo/galeria/$', views.galeria, name='galeria'),
    url(r'^acervo/galeria/(?P<slug>[\-\d\w]+)/$', views.geleria_detalhe, name='galery-detail'),
    url(r'^noticia/(?P<slug>[\-\d\w]+)/$', views.noticia, name='noticia'),
    url(r'^comunidades/$', views.community, name='comunidades'),
    url(r'^comunidade/(?P<slug>[\-\d\w]+)/$', views.comunidade, name='comunidade'),
]

rondon/urls.py
#coding=utf-8
"""rondon URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from core import views
from django.conf.urls.static import static

admin.site.site_title = "Concilia BR 381"
admin.site.site_header = "Concilia BR 381"
admin.site.index_title = 'Painel administrador do site'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^sobre/$', views.about, name='about'),
    url(r'^duvidas/$', views.duvida, name='faq'),
    url(r'^parceiros/$', views.partners, name='partners'),
    url(r'^conselho-executivo/$', views.conselho_executivo, name='conselho_executivo'),
    url(r'^manual-marca/$', views.manual_marca, name='manual_marca'),
    url(r'^conteudos/', include('content.urls', namespace='content')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nE-mail:{1}\n{2}'.format(name, email, message)
        send_mail(
            'Contato projeto Rondon', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

core/views.py
# coding=utf-8
from django.shortcuts import render
from .forms import ContactForm
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.views.generic import View, TemplateView, ListView
from content.models import Noticia, Timeline
from django.db.models import Q
from django.shortcuts import render_to_response
from django.template import RequestContext

User = get_user_model()


# Página inicial
class IndexView(ListView):
    context_object_name = 'noticias_home_page'
    queryset = Noticia.objects.filter(~Q(image='')).order_by('-published_at')[0:3]
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['timeline_itens'] = Timeline.objects.all()
        return context


# Página sobre o projeto
class AboutView(TemplateView):
    template_name = 'about.html'


# Página de parceiros
class PartnersView(TemplateView):
    template_name = 'partners.html'

# Página do manual da marca
class ManualMarcaView(TemplateView):
    template_name = 'manual_marca.html'


# Página Plano de Providencias
class PlanoProvidenciaView(TemplateView):
    template_name = 'plano_providencias.html'


# Página Criterios e regras
class CriteriosRegrasView(TemplateView):
    template_name = 'criterios_regras.html'


# Página Criterios e regras
class AcervoView(TemplateView):
    template_name = 'acervo.html'

# Página CMAR
class CmarView(TemplateView):
    template_name = 'cmar.html'

# Página Imóveis
class ImoveisView(TemplateView):
    template_name = 'imoveis.html'

# Página de contatos
def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
    elif request.method == 'POST':
        messages.error(request, 'Formulário inválido')
    context = {
        'form': form,
        'success': success,
    }
    return render(request, 'contact.html', context)


# HTTP Error 404
def page_not_found(request):
    return render(request, '404.html')


def server_error(request):
    return render(request,  '500.html')


index = IndexView.as_view()
about = AboutView.as_view()
partners = PartnersView.as_view()
manual_marca = ManualMarcaView.as_view()
plano_providencias = PlanoProvidenciaView.as_view()
criterios_regras = CriteriosRegrasView.as_view()
acervo = AcervoView.as_view()
cmar = CmarView.as_view()
imoveis = ImoveisView.as_view()

core/templates/_menu.html
 {% load static %}
<header>
     <div class="top-menu-container" id="external-menu">
        <nav class="main-ul-nav" style="font-weight: bold;">
            <div class="menu-header-menu-container" style="margin-left: 212px;">
                <ul id="menu-header-menu" class="menu">
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-19">
                        <a href="#">O Programa</a>
                        <div class="nav-sub-wrap ord-nav">
                            <div class="nsw">
                                <div class="nav-sub-menus">
                                    <ul>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                            <a href="{% url 'about' %}">O que é</a>
                                        </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26">
                                            <a href="{% url 'partners' %}">Parceiros</a>
                                        </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25">
                                            <a href="{% url 'conselho_executivo' %}">Conselho Executivo</a>
                                        </li>
                                         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25">
                                            <a target="_blank" href="http://portal.trf1.jus.br/sjmg/processual/anel-rodoviario/anel-rodoviario.htm">Ação Civil Pública</a>
                                         </li>

                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-2780">
                                            <a href="{% url 'manual_marca' %}">Manual de identidade visual</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-19">
                        <a href="">Comunidades</a>
                        <div class="nav-sub-wrap ord-nav">
                            <div class="nsw">
                                <div class="nav-sub-menus">
                                    <ul>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                            <a href="{% url 'content:comunidades' %}">Comunidades Seladas</a>
                                        </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                            <a href="{% url 'cmar' %}" title="CMAR - COMUNIDADE DE MORADORES EM ÁREAS DE RISCOS">CMAR</a>
                                        </li>
                                        {% for comunidade in comunidades %}
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-2780">
                                            <a href="{{comunidade.get_absolute_url}}">{{comunidade}}</a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li id="menu-item-18" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18">
                        <a href="{% url 'imoveis' %}">Imóveis</a>
                    </li>
                    <li id="menu-item-53" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-54">
                        <a href="">PROVIDÊNCIAS</a>
                        <div class="nav-sub-wrap ord-nav">
                            <div class="nsw">
                                <div class="nav-sub-menus">
                                    <ul>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                            <a href="{% url 'plano_providencias' %}">PLANO DE PROVIDÊNCIAS</a>
                                        </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25">
                                            <a href="{% url 'criterios_regras' %}">CRITÉRIOS E REGRAS</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li id="menu-item-56" class="menu-item menu-item-type-taxonomy menu-item-object-category">
                        <a href="{% url 'content:noticias' %}">Notícias</a>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page">
                        <a href="{% url 'acervo' %}">ACERVO</a>
                        <div class="nav-sub-wrap ord-nav">
                            <div class="nsw">
                                <div class="nav-sub-menus">
                                    <ul>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                            <a href="{% url 'content:galeria' %}">FOTOS</a>
                                        </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26">
                                            <a href="{% url 'content:videos' %}">VIDEOS</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li id="menu-item-57" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-54">
                        <a href="{% url 'content:perguntas-frequentes' %}">Dúvidas</a>
                    </li>
                    <li id="menu-item-54" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-54">
                        <a href="{% url 'contact' %}">Contato</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="row">
        <div>
            <div class="image-block">
                <h1>
                    <a class="logo_marca"
                    style="background: url({% static 'img/concilia.png' %}) no-repeat center 0px #fff; margin-top: 0px;"
                    href="{% url 'index' %}">
                        Concilia BR 381</a>
                </h1>
            </div>
        </div>
    </div>
    <section id="big-map" class="image_header hide-for-small" >
        <!--<div class="image-header-left"></div>-->
        <!--<div class="image-block">-->
                <!--<div class="logo_marca"></div>-->
        <!--</div>-->

    </section>
</header>
<div class="top-border medium-down"></div>

core/templates/acervo.html
{% extends "base.html" %}

{% block title %}
    Acervo | {{ block.super }}
{% endblock  %}

{% block content %}

<section class="section-about">
    <div class="row">
        <h1 class="title-header-section">Acervo</h1>
    </div>
</section>
<section class="section-about">
    <div class="row">
        <div class="col-sm-6">
            <h4>
                <a href="{% url 'content:galeria' %}">
                    <img src="http://www.favelaeissoai.com.br/wp-content/themes/favela2014/img/favela_radio.jpg">
                    <h2>Fotos</h2>
                </a>
            </h4>
        </div>
        <div class="col-sm-6">
            <h4>
                <a href="{% url 'content:videos' %}">
                    <img src="http://www.favelaeissoai.com.br/wp-content/themes/favela2014/img/gravacoes_dos_artistas.jpg">
                    <h2>Vídeos</h2>
                </a>
            </h4>
        </div>
    </div>
</section>
{% endblock  %}

core/templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="pt-br">

<head>
    <!-- ################################################  -->
    <!-- #                                              #  -->
    <!-- # WEBSITE DESENVOLVIDO POR @LUCASLAMOUNIER     #  -->
    <!-- #                                              #  -->
    <!-- #                                              #  -->
    <!-- ################################################  -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=" " />
    <title>{% block title %} Concilia BR-381 e Anel {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'foundation-icons/foundation-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery.bxslider.css' %}" />
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
</head>

<body>
    <div class="off-canvas-wrap" data-offcanvas>
        <div class="inner-wrap">

             <!-- Menu responsivo -->

            <div class="top-border hide-for-medium-down"></div>
            <nav class="tab-bar mobile-tab-bar show-for-medium-down" data-topbar>

                <section class="right-small mobile-right-small">
                    <a href="{% url 'index' %}">
                        <img src="{% static 'img/concilia_without_text.png' %}" />
                    </a>
                </section>

                <section class="middle tab-bar-section center-text">
                    <a href="{% url 'index' %}">
                        <h1 class="title-sm-mobile">Concilia BR 381 e Anel</h1>
                    </a>
                </section>

                <section class="left-small">
                    <a class="left-off-canvas-toggle menu-icon" href="#" title="menu"><span></span></a>
                </section>

            </nav>
            <aside class="left-off-canvas-menu" id="menu-mobile">
                <ul class="off-canvas-list">
                    <li class="menu-item menu-item-root menu-item-type-post_type menu-item-object-page menu-item-has-children">
                        <button class="button-sub-menu">O Programa </button>
                        <div class="nav-sub-wrap ord-nav">
                            <div class="nsw">
                                <div class="nav-sub-menus">
                                    <ul>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page">
                                            <a class="mobile-submenu-item" href="{% url 'about' %}">O que é</a>
                                        </li>

                                        <li class="menu-item menu-item-type-post_type menu-item-object-page">
                                            <a class="mobile-submenu-item" href="{% url 'partners' %}">Parceiros</a>
                                        </li>
                                         <li class="menu-item menu-item-type-post_type menu-item-object-page">
                                             <a href="{% url 'conselho_executivo' %}">Conselho Executivo</a>
                                        </li>
                                         <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25">
                                            <a target="_blank" href="http://portal.trf1.jus.br/sjmg/processual/anel-rodoviario/anel-rodoviario.htm">Ação Civil Pública</a>
                                         </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children">
                                            <a href="{% url 'manual_marca' %}">Manual de identidade visual</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>

                    <li class="menu-item menu-item-root menu-item-type-post_type menu-item-object-page menu-item-has-children">
                        <button class="button-sub-menu">Comunidades </button>
                        <div class="nav-sub-wrap ord-nav">
                            <div class="nsw">
                                <div class="nav-sub-menus">
                                    <ul>
                                       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                            <a href="{% url 'content:comunidades' %}">Comunidades Seladas</a>
                                        </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                             <button class="button-sub-menu" onclick="window.location.href='{% url 'cmar' %}'"
                                                     title="CMAR - COMUNIDADE DE MORADORES EM ÁREAS DE RISCOS">CMAR</button>
                                        </li>
                                        {% for comunidade in comunidades %}
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-2780">
                                            <button class="button-sub-menu" onclick="window.location.href='{{comunidade.get_absolute_url}}'">{{comunidade}}</button>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>

                    <li class="menu-item menu-item-root menu-item-type-post_type menu-item-object-page">
                         <button class="button-sub-menu" onclick="window.location.href='{% url 'imoveis' %}'">Imóveis </button>
                    </li>
                    <li id="menu-item-53" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-54">
                        <button class="button-sub-menu">Providências</button>
                        <div class="nav-sub-wrap ord-nav">
                            <div class="nsw">
                                <div class="nav-sub-menus">
                                    <ul>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                            <button class="button-sub-menu" onclick="window.location.href='{% url 'plano_providencias' %}'">Plano de Providências</button>
                                        </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-25">
                                            <button class="button-sub-menu" onclick="window.location.href='{% url 'criterios_regras' %}'">Critérios e Regras</button>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="menu-item menu-item-root menu-item-type-taxonomy menu-item-object-category">
                        <button class="button-sub-menu" onclick="window.location.href='{% url 'content:noticias' %}'">Notícias </button>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page">
                         <button class="button-sub-menu">Acervo </button>
                        <div class="nav-sub-wrap ord-nav">
                            <div class="nsw">
                                <div class="nav-sub-menus">
                                    <ul>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24">
                                            <button class="button-sub-menu" onclick="window.location.href='{% url 'content:galeria' %}'">Fotos</button>
                                        </li>
                                        <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-26">
                                            <button class="button-sub-menu" onclick="window.location.href='{% url 'content:videos' %}'">Vídeos</button>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="menu-item menu-item-root menu-item-type-post_type menu-item-object-page">
                        <button class="button-sub-menu" onclick="window.location.href='{% url 'content:perguntas-frequentes' %}'">Dúvidas </button>

                    </li>
                    <li class="menu-item menu-item-root menu-item-type-post_type menu-item-object-page">
                        <button class="button-sub-menu" onclick="window.location.href='{% url 'contact' %}'">Contato </button>

                    </li>
                </ul>
            </aside>

             <!-- Menu -->

            {% include "_menu.html" %}

            <!-- Conteúdos da página -->


            <!--<div class="container-fluid">-->
             <div >
                <button onclick="topFunction()" id="BtnTopo" title="Ir para o topo"> Topo </button>
                {% block content %}{% endblock %}

            </div>

            <!-- Rodapé -->
            <div class="line-separator-gray"></div>
            <footer>
                <div class="row" style="margin-bottom: 25px;">
                        <div class="col-sm-3">
                            <p class="label-rodape">Apoio:</p>
                            <a href="{% url 'partners' %}" target="_blank" title="Comunidade dos Moradores do Anel Rodoviário - CMAR">
                                <img class="footer-image-apoio img-responsive" src="{% static 'img/logomarcas/CMAR2.png' %}" alt="Comunidade dos Moradores do Anel Rodoviário - CMAR" />
                            </a>
                        </div>
                        <div class="col-sm-9">
                            <p class="label-rodape">Parceria:</p>
                             <a class="" href="{% url 'partners' %}" target="_blank" title="Realização e Parceria">
                               <img class="footer-image-apoio img-responsive" src="{% static 'img/logomarcas/apoio2.png' %}" alt="Apoio" />
                             </a>
                        </div>
                </div>

                <!--<br />-->
                <div class="row">
                    <div class="col-sm-12">
                        <p class="label-rodape" style="position: absolute;">Realização:</p>

                        <a class="" href="{% url 'partners' %}" target="_blank" title="Realização e Parceria">
                            <img class="footer-image img-responsive" src="{% static 'img/logomarcas/realizacao2.png' %}" alt="Realização" />
                        </a>
                    </div>
                </div>
            </footer>
            <a href="#" class="seta-cima"></a>
            <div class="rodape_end_background">
                <div class="row" style="text-align: center;">
                    <p style="margin-top: 40px;font-weight: bold; color: white;">&copy; Copyright 2017 Concilia BR-381 e Anel</p>
                </div>
            </div>
        </div>

    </div>

    <!-- Bibliotecas requeridas pelo sistema -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/foundation.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $(document).ready(function () {
                // Mobile Menu hide and show
                $('#menu-mobile ul li').mouseenter(function() {
                    $(this).children('div').show();
                });

                $('#menu-mobile ul li').mouseleave(function(){
                     $(this).children('div').hide();
                });
        });
    </script>

</body>

</html>

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}